---
title: Namkeen
url: khattak.info/namkeen
description: "This collection of themes takes queues from NUST branding and using beamer as LaTeX template." 
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
